### ISSUE TITLE
Current Drawing Tool Indicator

### ISSUE THREAD

**Issue by Technickel-Dev** [Technickel-Dev/low-poly#27]
There is no way to see what mode you are in for the Draw Preview. I would like to add some kind of indicator in that part of the UI to let the user know their current tool

**Comment by ignoreintuition** [comment]
Submitted a PR for this issue: https://github.com/Technickel-Dev/low-poly/pull/51

**Comment by Technickel-Dev** [comment]
Thanks again for the contribution!
